export enum SignupActionTypes {
  SIGNIN_SUCCESS = "SIGNIN",
  SIGNIN_ERROR = "SIGNIN_ERROR",
}
export enum LoginActionTypes {
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_ERROR = "LOGIN_ERROR",
}

export enum CategoryActionTypes {
  CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS",
  CREATE_CATEGORY_ERROR = "CREATE_CATEGORY_ERROR",
  RETRIEVE_CATEGORIES_SUCCESS = "RETRIEVE_CATEGORIES_SUCCESS",
  RETRIEVE_CATEGORIES_ERROR = "RETRIEVE_CATEGORIES_ERROR",
}

export enum TodosActionTypes {
  RETRIEVE_TODOS_SUCESS = "RETRIEVE_TODOS_SUCESS",
  RETRIEVE_TODOS_ERROR = "RETRIEVE_TODOS_ERROR",
  CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS",
  CREATE_TODO_ERROR = "CREATE_TODO_ERROR",
  DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS",
  DELETE_TODO_ERROR = "DELETE_TODO_ERROR",
}
